"""Generic application templates for Borealis MCP."""

from typing import List

from borealis_mcp.config.system import SystemConfig


class GenericTemplates:
    """PBS submit script templates for generic jobs."""

    @staticmethod
    def generate_submit_script(
        system_config: SystemConfig,
        executable: str,
        arguments: str,
        account: str,
        num_nodes: int,
        mpi_ranks_per_node: int,
        walltime: str,
        queue: str,
        job_name: str,
        environment_setup: str,
        modules: List[str],
    ) -> str:
        """
        Generate a generic PBS submit script.

        Args:
            system_config: System configuration
            executable: Path to executable or command
            arguments: Command-line arguments
            account: PBS account/project name
            num_nodes: Number of nodes
            mpi_ranks_per_node: MPI ranks per node
            walltime: Wall time in HH:MM:SS format
            queue: Queue name
            job_name: Name for the PBS job
            environment_setup: Custom environment setup commands
            modules: List of modules to load

        Returns:
            Complete PBS submit script as string
        """
        # Default filesystems
        default_fs = ":".join(system_config.default_filesystems)

        # Calculate total ranks
        total_ranks = num_nodes * mpi_ranks_per_node

        # Build module load commands
        module_cmds = "\n".join([f"module load {mod}" for mod in modules])
        module_section = module_cmds if module_cmds else "# No modules specified"

        # Environment setup section
        env_section = (
            environment_setup if environment_setup else "# No custom environment setup"
        )

        # Build arguments string
        args_str = f" {arguments}" if arguments else ""

        return f"""#!/bin/bash -l
#PBS -l select={num_nodes}:ncpus={system_config.cores_per_node}
#PBS -l walltime={walltime}
#PBS -l filesystems={default_fs}
#PBS -q {queue}
#PBS -A {account}
#PBS -N {job_name}

# System: {system_config.display_name}
# Generated by Borealis MCP

cd $PBS_O_WORKDIR

# Load modules
{module_section}

# Custom environment setup
{env_section}

# Job parameters
NNODES={num_nodes}
NRANKS_PER_NODE={mpi_ranks_per_node}
NTOTRANKS={total_ranks}

echo "========================================"
echo "Generic Job: {job_name}"
echo "========================================"
echo "System: {system_config.display_name}"
echo "Nodes: $NNODES"
echo "Ranks per node: $NRANKS_PER_NODE"
echo "Total ranks: $NTOTRANKS"
echo "Executable: {executable}"
echo "========================================"
echo ""

# Run the executable
mpiexec -n $NTOTRANKS -ppn $NRANKS_PER_NODE {executable}{args_str}

RET=$?

echo ""
echo "========================================"
echo "Job completed with exit code: $RET"
echo "========================================"

exit $RET
"""
