"""Hello World application templates for Borealis MCP."""

from typing import Any, Dict, List

from borealis_mcp.config.system import SystemConfig


class HelloWorldTemplates:
    """PBS submit script templates for Hello World."""

    @staticmethod
    def generate_submit_script(
        system_config: SystemConfig,
        num_nodes: int,
        ranks_per_node: int,
        walltime: str,
        queue: str,
        job_name: str,
        account: str,
        modules: List[str],
        mpi_command: str,
        mpi_flags: List[str],
        env_vars: Dict[str, Any],
    ) -> str:
        """
        Generate MPI Hello World submit script.

        The script prints rank number and hostname from each MPI process.

        Args:
            system_config: System configuration
            num_nodes: Number of nodes to use
            ranks_per_node: MPI ranks per node
            walltime: Wall time in HH:MM:SS format
            queue: Queue name
            job_name: Name for the PBS job
            account: PBS account/project name
            modules: List of modules to load
            mpi_command: MPI launch command (e.g., "mpiexec")
            mpi_flags: Additional MPI flags
            env_vars: Environment variables to set

        Returns:
            Complete PBS submit script as string
        """
        # Build module load commands
        module_cmds = "\n".join([f"module load {mod}" for mod in modules])

        # Build environment variable exports
        env_cmds = "\n".join(
            [f"export {key}={value}" for key, value in env_vars.items()]
        )
        env_section = env_cmds if env_cmds else "# No additional environment variables"

        # Build MPI flags string
        flags_str = " ".join(mpi_flags) if mpi_flags else ""

        # Default filesystems
        default_fs = ":".join(system_config.default_filesystems)

        # Calculate total ranks
        total_ranks = num_nodes * ranks_per_node

        return f"""#!/bin/bash -l
#PBS -l select={num_nodes}:ncpus={system_config.cores_per_node}
#PBS -l walltime={walltime}
#PBS -l filesystems={default_fs}
#PBS -q {queue}
#PBS -A {account}
#PBS -N {job_name}

# System: {system_config.display_name}
# Total Ranks: {total_ranks} ({num_nodes} nodes x {ranks_per_node} ranks/node)
# Generated by Borealis MCP

cd $PBS_O_WORKDIR

# Load modules
{module_cmds}

# Set environment
{env_section}

# Calculate MPI parameters
NNODES={num_nodes}
NRANKS_PER_NODE={ranks_per_node}
NTOTRANKS={total_ranks}

echo "========================================"
echo "Hello World MPI Job"
echo "========================================"
echo "System: {system_config.display_name}"
echo "Nodes: $NNODES"
echo "Ranks per node: $NRANKS_PER_NODE"
echo "Total ranks: $NTOTRANKS"
echo "========================================"
echo ""

# Run Hello World - each rank prints its rank number and hostname
{mpi_command} -n $NTOTRANKS -ppn $NRANKS_PER_NODE {flags_str} bash -c '\\
    echo "Hello from rank ${{PMI_RANK:-${{PMIX_RANK:-${{OMPI_COMM_WORLD_RANK:-unknown}}}}}} on $(hostname)"'

echo ""
echo "========================================"
echo "Hello World completed successfully"
echo "========================================"
"""
